//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landlord.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public long Id { get; set; }
        public long PropertyId { get; set; }
        public Nullable<long> TennantId { get; set; }
        public Nullable<long> TennantPreviousId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Tennant Tennant { get; set; }
        public virtual Tennant Tennant1 { get; set; }
    }
}
