//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landlord.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public long Id { get; set; }
        public byte[] Data { get; set; }
        public string Description { get; set; }
        public Nullable<long> FurnitureId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<long> TennantId { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual Property Property { get; set; }
        public virtual Room Room { get; set; }
        public virtual Tennant Tennant { get; set; }
    }
}
